# Build the image with Nix first:
#   nix build .#docker-image && docker load < ./result
services:
  app:
    container_name: vtraty-pes-bot
    image: vtraty-pes-bot
    restart: unless-stopped
    command: --config ${CONFIG_PATH}
    volumes:
       - ./data:/usr/src/app/data
    env_file:
       - .env
